# Copyright (c) 2023, 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
jifa:
  role: standalone-worker
  storage-path: ${user.home}/jifa-storage
  database-host: ${MYSQL_HOST:}
  database-name: ${MYSQL_DATABASE:jifa}
  database-user: ${MYSQL_USER:jifa}
  database-password: ${MYSQL_PASSWORD:jifa}
  disabled-file-transfer-methods: [ scp ]

spring:
  servlet:
    multipart:
      max-request-size: 512MB
      max-file-size: 512MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  task.scheduling.pool.size: 8

server:
  tomcat:
    relaxed-query-chars:
      - '['
      - ']'